Botón de exportación de reporte de encuestas a CSV Front (Web)
salgue441/Net-Zero-Citizens pull request #107
Opened 2023-09-27 22:25 UTC by OlimpiaGarcia

# Botón de exportación de reporte de encuestas a CSV Front (Web)

| US ID | Module | User Story                                                                  | System  | Priority | Size | Testing | Documentation |
| ----- | ------ | --------------------------------------------------------------------------- | ------- | -------- | ---- | ------- | ------------- |
| 61   | REPORTE | Seleccionar productos que ofrece una empresa al registrar una nueva empresa | Admin | High     |  x    | Done    | Done          |

### Description

Como OSF quiero tener la posibilidad de visualizar un botón para descargar los reportes de las encuestas con toda la información detallada de una encuesta en un archivo CSV para poder visualizarla de manera más detallada.

### Acceptance Criteria

- [x] Visualizar el botón de descargar reporte dentro de una encuesta ya cerrada
- [] Dar clic en el botón para comenzar la descarga

## UI Design (or Program Flow)

![image](https://github.com/salgue441/Net-Zero-Citizens/assets/93570664/bf45729e-2738-4ad1-994d-ed59bb08ea69)

## Additional Changes

Any changes that are not covered by the user story and acceptance criteria (if any).

2023-09-27 23:50 UTC, sgarnica1 approved these changes, later dismissed

2023-09-28 00:16 UTC, yna2131 approved these changes, later dismissed

2023-09-28 00:34 UTC, santiagordz requested changes
Porfis actualicen con dev cuando puedan

2023-09-28 00:39 UTC, santiagordz submitted a review, later dismissed

2023-09-28 01:04 UTC, DanielSebasCM commented on Admin/.env_template
> -NEXTAUTH_SECRET=YOUR_SECRET
Please dont delete the template, revive it

2023-09-28 01:05 UTC, DanielSebasCM requested changes

2023-09-28 01:05 UTC, DanielSebasCM commented on Admin/.env_template
> -NEXTAUTH_SECRET=YOUR_SECRET
Please dont delete templates, revive it

2023-09-28 01:45 UTC, OlimpiaGarcia commented on Admin/.env_template
> -NEXTAUTH_SECRET=YOUR_SECRET
ya

2023-09-28 01:46 UTC, VON0222 approved these changes

2023-09-28 01:46 UTC, DanielSebasCM approved these changes

2023-09-28 01:46 UTC, merged