Mapa definitivo
salgue441/Net-Zero-Citizens pull request #138
Opened 2023-09-28 22:42 UTC by JP-coder2000

En esta parte estoy creando tanto el front como el back en iOS de visualizar los proovedores en el mapa.

2023-09-28 22:55 UTC, dembA7 requested changes, later dismissed
descomentar el middleware de validateToken

2023-09-29 05:44 UTC, danfupo03 commented on ios/GreenCircle/GreenCircle/GreenCircleApp.swift
Descomenta el Coordinator View

2023-09-29 05:46 UTC, danfupo03 reviewed
Si quieres añade el mapa a la Tab Bar ahí un espacio justo para eso

2023-09-29 16:07 UTC, JP-coder2000 commented on ios/GreenCircle/GreenCircle/GreenCircleApp.swift
Listo, gracias por el comentario.

2023-09-29 16:31 UTC, CharlesVela66 submitted a review, later dismissed

2023-09-29 17:08 UTC, closed without merging