Ios/marines/terminos&provacidad
salgue441/Net-Zero-Citizens pull request #147
Opened 2023-09-30 00:15 UTC by Gamaliel-Marines

[Permite al usuario, específicamente a alguien registrándose cómo proveedor, consultar aviso de términos & condiciones de privacidad.](https://github.com/salgue441/Net-Zero-Citizens/pull/146)

2023-09-30 00:19 UTC, DHurtado714-itesm requested changes
Poner un screen shot de la UI en el PR

2023-09-30 00:26 UTC, Gamaliel-Marines commented
> Poner un screen shot de la UI en el PR
<img width="419" alt="Screenshot 2023-09-29 at 6 25 30 PM" src="https://github.com/salgue441/Net-Zero-Citizens/assets/110830802/79ea2fe4-a83c-47bb-baa3-dd7b788d65a7">
<img width="457" alt="Screenshot 2023-09-29 at 6 25 49 PM" src="https://github.com/salgue441/Net-Zero-Citizens/assets/110830802/14791aa9-83a2-40cc-a187-a72edd7a7ee0">

2023-09-30 00:28 UTC, Riosmena submitted a review, later dismissed
<img src="https://i.pinimg.com/564x/ee/12/a9/ee12a906d097550141060360ccc54fd2.jpg">

2023-09-30 01:03 UTC, salgue441 submitted a review, later dismissed

2023-09-30 03:50 UTC, danfupo03 requested changes
Has una vista aparte donde pongas el aviso de privacidad y has que solo se llame la vista. Porque saturas esa vista y en caso de que debamos trabajar con ella está todo el aviso estorbando. Porfa

2023-09-30 04:48 UTC, DHurtado714-itesm commented
Mañana lo corro en mi Xcode, pero se ve bien

2023-10-04 04:02 UTC, DHurtado714-itesm submitted a review, later dismissed

2023-10-04 17:39 UTC, DanyGuti submitted a review, later dismissed

2023-10-04 20:01 UTC, lCDSLl-Richard requested changes, later dismissed

2023-10-04 20:01 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Presentation/Views/Login/CompanyRegisterView.swift
Todo ese comment no fue movido ya a un archivo no? Para mejor borrarlo

2023-10-05 00:46 UTC, danfupo03 approved these changes
Ahora si 👍

2023-10-05 21:43 UTC, Riosmena approved these changes
<img src="https://i.pinimg.com/564x/ee/12/a9/ee12a906d097550141060360ccc54fd2.jpg">

2023-10-05 22:43 UTC, Gamaliel-Marines commented on ios/GreenCircle/GreenCircle/Presentation/Views/Login/CompanyRegisterView.swift
Según yo ya no hay ningún comment

2023-10-05 23:42 UTC, merged

2023-10-11 02:55 UTC, Gdakgdak22 approved these changes