Subir documentos de validación de la empresa en el registro de nueva empresa (Android)
salgue441/Net-Zero-Citizens pull request #149
Opened 2023-09-30 00:57 UTC by santiagordz

Como Proveedor quiero subir mis documentos de la empresa para que la administración de la app pueda verificar mi identidad y aprobar mi empresa dentro de su catálogo de empresas de confianza

### CRITERIOS DE ACEPTACIÓN

El Proveedor puede

- [x ]  Subir un PDF con la INE del representante legal de su empresa al momento de registrarse en la app móvil
- [ x]  Subir un PDF con la Acta Constitutiva de su empresa al momento de registrarse en la app móvil
- [ x]  Subir un PDF con el Curriculum de mi empresa donde vengan:
- Presentación curricular (documento)
- Listado de productos y servicios a ofrecer
- Constancia de 5 proyectos verificables realizados con la tecnología ofertada
- [ x]  Subir un PDF con el Comprobante Directorio de Instaladores Certificados de la CDMX en caso de tenerlo (opcional)
- [ x]  Subir un PDF con el Comprobante Padrón de Empresas Especializadas FIDE en caso de tenerlo (opcional)
- [ x]  Subir un PDF con las certificaciones de sus sistemas fotovoltaicos en caso de ofrecerlos
- [ x]  Subir un PDF con las certificaciones de sus calentadores solares en caso de ofrecerlos
- [ x]  Subir un PDF con la carta compromiso de seguridad y garantía
- [ x]  Enviar todo el registro con los documentos ya registrados

VISTAS

## Agregar Empresa de Prueba
![image](https://github.com/salgue441/Net-Zero-Citizens/assets/67066757/0fc9fba7-51bb-44a4-9325-5572607778dd)

##  Vista para subir archivos
![image](https://github.com/salgue441/Net-Zero-Citizens/assets/67066757/c75b913e-784c-4f86-8450-e7b4c70f3e28)

## Dialog Para esocger archivo
![image](https://github.com/salgue441/Net-Zero-Citizens/assets/67066757/e2cdf2ed-dce3-4f97-870a-0a0bdd763384)

## Archivo Seleccionado (Boton Subir Abilitado)
![image](https://github.com/salgue441/Net-Zero-Citizens/assets/67066757/110a50ba-a6a9-4571-b1cb-76e770d0a590)

## Archivo Arriba en S3
![image](https://github.com/salgue441/Net-Zero-Citizens/assets/67066757/6b3ceef7-eabd-4de0-89fb-90f76e45b76c)

2023-09-30 01:03 UTC, JP-coder2000 commented
Hola, te recomiendo actualizar el unit test.

2023-09-30 01:09 UTC, DHurtado714-itesm requested changes, later dismissed

2023-09-30 01:09 UTC, DHurtado714-itesm commented on backend/form.html
Borra este archivo

2023-09-30 01:09 UTC, DHurtado714-itesm commented on backend/index.ts
esto tambien

2023-09-30 01:09 UTC, DHurtado714-itesm commented on backend/src/controllers/companyFiles.controller.ts
> +    // Format the string from android petitions
Para iOS, funcion de una forma diferente

2023-09-30 01:09 UTC, DHurtado714-itesm commented on backend/src/controllers/companyFiles.controller.ts
> +      fileDescription as FileDescription | 'INE representante legal', // TODO: Cambiar este valor
esto esta hardcoded

2023-09-30 01:09 UTC, DHurtado714-itesm commented on backend/src/controllers/companyFiles.controller.ts
> +    return res.status(200).send('File uploaded!')
que envie un json como status

      return res.status(200).json({ message: 'File uploaded' })

2023-10-01 23:01 UTC, DHurtado714-itesm approved these changes
Se ve muy bien, solo unas pequenas cosas que quitar para hacer merge

2023-10-01 23:01 UTC, DHurtado714 commented on backend/form.html
Borra el form muri

2023-10-01 23:01 UTC, DHurtado714 commented on backend/index.ts
tambien esto

2023-10-01 23:01 UTC, DHurtado714 commented on backend/src/controllers/companyFiles.controller.ts
> +      fileDescription as FileDescription | 'INE representante legal', // TODO: Cambiar este valor
des harcodea esto

2023-10-02 04:16 UTC, salgue441 commented on Android/GreenCircle/app/src/main/java/com/greencircle/framework/views/fragments/company/upload_documents/UploadDocumentDialogFragment.kt
> +    private fun uploadFile(file: File) {
Hay algun motivo porque esta funcion mantiene el comentario de TODO?

2023-10-02 04:18 UTC, salgue441 requested changes

2023-10-02 04:18 UTC, salgue441 commented on Android/GreenCircle/app/src/main/java/com/greencircle/framework/views/fragments/company/upload_documents/UploadDocumentDialogFragment.kt
> +        // TODO: Change to real companyId
Hay algun motivo porque esta funcion tiene el comment de TODO: Change to real company ID?

2023-10-02 04:19 UTC, salgue441 commented
Como nota final: tienen conflictos con los nuevos cabmios de develop

2023-10-02 14:03 UTC, closed without merging