iOS/DaniG/CheckFavProv
salgue441/Net-Zero-Citizens pull request #156
Opened 2023-10-01 16:37 UTC by DanyGuti

# User Story

| US ID | Module | User Story                                                                  | System  | Priority | Size | Testing | Documentation |
| ----- | ------ | --------------------------------------------------------------------------- | ------- | -------- | ---- | ------- | ------------- |
| 255   | PERFIL CLIENTE-CATALOGO   | Marcar proveedores como favoritos | iOS | Low     | 3    | Done    | Done          |

### Description

Como cliente quiero marcar proveedores como favoritos para poder recordarlos fácilmente.

### Acceptance Criteria

- [x] Marcar un proveedor como favorito desde el catálogo de proveedores
- [x] Marcar un proveedor como favorito desde el perfil de un proveedor
- [x] Visualizar un mensaje de éxito tras marcar a un proveedor como favorito

## UI Design (or Program Flow)

<table>
<tr>
<img width="367" alt="Screenshot 2023-10-01 at 2 48 36" src="https://github.com/salgue441/Net-Zero-Citizens/assets/105307817/f408052f-9621-4b5b-8365-27b2478ac7e7">
<img width="364" alt="Screenshot 2023-10-01 at 2 50 39" src="https://github.com/salgue441/Net-Zero-Citizens/assets/105307817/d1a947d5-7ac2-4d10-8d40-b0caa4e4531c">

</tr>
</table>

## Additional Changes

* Se agregó backend y tests de tabla "Favourites"
* Se separó ContactCompanyView.swift en diferentes components
* Se eliminó print email de CompanyUseCase.swift

2023-10-01 17:06 UTC, CharlesVela66 requested changes

2023-10-01 17:06 UTC, CharlesVela66 commented on backend/src/routes/favourite.routes.ts
> +router.get('/:userId', controller.getAllFavouritesByUser)
Las rutas GET de "/:favouriteId" y "/:userId" pueden entrar en conflicto porque tienen el mismo prefijo y las dos son dinamicas. Es decir, que si yo quiero obtener los favoritos por usuario y llamo al back con 'localhost:4000/api/v1/favourites/{id}' me puede estar llamando la funcion de getFavouriteById en lugar de getAllFavouritesByUser

2023-10-01 17:07 UTC, CharlesVela66 commented on backend/src/routes/favourite.routes.ts
> +router.get('/:userId', controller.getAllFavouritesByUser)
Por lo demás, lo veo muy bien

2023-10-01 17:35 UTC, dvegaa20 approved these changes, later dismissed

2023-10-01 17:59 UTC, CharlesVela66 approved these changes

2023-10-02 03:50 UTC, DHurtado714-itesm approved these changes

2023-10-02 03:50 UTC, merged