Android/muri/merge
salgue441/Net-Zero-Citizens pull request #190
Opened 2023-10-03 22:34 UTC by DHurtado714-itesm

# User Story

| US ID | Module | User Story                                                                  | System  | Priority | Size | Testing | Documentation |
| ----- | ------ | --------------------------------------------------------------------------- | ------- | -------- | ---- | ------- | ------------- |
| 261   | AUTH   | Subir Archivos de proveedor | Android/iOS | High     | 5    | Done    | Done          |

### Description

Como Proveedor quiero subir mis documentos de la empresa para que la administración de la app pueda verificar mi identidad y aprobar mi empresa dentro de su catálogo de empresas de confianza

### Acceptance Criteria

- [ x ]  Subir un PDF con la INE del representante legal de su empresa al momento de registrarse en la app móvil
- [x ]  Subir un PDF con la Acta Constitutiva de su empresa al momento de registrarse en la app móvil
- [x ]  Subir un PDF con el Curriculum de mi empresa donde vengan:
- Presentación curricular (documento)
- Listado de productos y servicios a ofrecer
- Constancia de 5 proyectos verificables realizados con la tecnología ofertada
- [ x]  Subir un PDF con el Comprobante Directorio de Instaladores Certificados de la CDMX en caso de tenerlo (opcional)
- [ x]  Subir un PDF con el Comprobante Padrón de Empresas Especializadas FIDE en caso de tenerlo (opcional)
- [x ]  Subir un PDF con las certificaciones de sus sistemas fotovoltaicos en caso de ofrecerlos
- [x ]  Subir un PDF con las certificaciones de sus calentadores solares en caso de ofrecerlos
- [ x]  Subir un PDF con la carta compromiso de seguridad y garantía
- [ x]  Enviar todo el registro con los documentos ya registrados

## UI Design (or Program Flow)

<img width="113" alt="Screenshot 2023-10-03 at 16 33 10" src="https://github.com/salgue441/Net-Zero-Citizens/assets/81983296/5b764321-447c-48ad-ae97-0cda00aaae94">

2023-10-04 04:40 UTC, salgue441 approved these changes

2023-10-04 04:40 UTC, salgue441 commented on Android/GreenCircle/app/src/main/java/com/greencircle/framework/views/fragments/company/upload_documents/UploadDocumentsFragment.kt
> +            ActivityCompat.requestPermissions(
Ya hay un modal al inicio de la app que pide los permisos, si pueden mover el request de permisos a esa vista. Se llama RequestPermissons.kt. 

Si es adicional, solo añadan los permisos al array para que el usuario los acepte al iniciar la app por primera vez

2023-10-04 04:41 UTC, Gamaliel-Marines submitted a review, later dismissed

2023-10-04 04:43 UTC, salgue441 requested changes

2023-10-04 04:43 UTC, salgue441 commented on Android/GreenCircle/app/src/main/java/com/greencircle/framework/views/fragments/company/upload_documents/UploadDocumentsFragment.kt
> +                STORAGE_PERMISSION_REQUEST_CODE
Ya hay un modal al inicio de la app que pide los permisos, si pueden mover el request de permisos a esa vista. Se llama RequestPermissons.kt.

Si es adicional, solo añadan los permisos al array para que el usuario los acepte al iniciar la app por primera vez

2023-10-04 04:45 UTC, Gamaliel-Marines commented on Android/GreenCircle/app/src/main/java/com/greencircle/framework/views/fragments/company/upload_documents/UploadDocumentsFragment.kt
> +                STORAGE_PERMISSION_REQUEST_CODE
Espero a esto para hacer el approve

2023-10-04 04:49 UTC, salgue441 commented on Android/GreenCircle/app/src/main/java/com/greencircle/framework/views/fragments/company/upload_documents/UploadDocumentsFragment.kt
> +                STORAGE_PERMISSION_REQUEST_CODE
Si porfa, para que ya quede eso bien en android

2023-10-04 04:56 UTC, salgue441 submitted a review, later dismissed

2023-10-04 04:59 UTC, dembA7 submitted a review, later dismissed

2023-10-04 05:15 UTC, dembA7 approved these changes, later dismissed

2023-10-04 14:06 UTC, CharlesVela66 commented
IMPORTANTE

Con estos cambios, la visualización de los archivos en Admin Dashboard no va a funcionar. En este mismo momento ya se está tomando acción para que Admin se adapte a estos cambios.

2023-10-04 18:37 UTC, lCDSLl-Richard requested changes, later dismissed

2023-10-04 18:37 UTC, lCDSLl-Richard commented on backend/.env_template
Por qué se elimino la template?

2023-10-04 18:37 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Data/Remote/Network/NetworkAPIService.swift
> +            let response = try await AF.upload(multipartFormData: { multipartFormData in
En vez de usar el local service y sacar los tokens, pueden usar la session que ya tiene por default los tokens.

Cambiariamos
```swift
let res = AF.upload...
```
Por
```swift
let res = session.upload...
```

2023-10-04 18:37 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Data/Repository/UserRepository.swift
> +        print("User: \(authData.user)")
Hay que quitar el print

2023-10-04 18:37 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Domain/Models/Companies/CompanFilesModel.swift
> +//    init(companyFileId: UUID = UUID(),
Si no se va a usar el comment, mejor quitarlo.

2023-10-04 18:37 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Presentation/ViewModels/Company/CompanyViewModel.swift
> +    init(useCase: CompanyUseCase = CompanyUseCase.shared, repository: CompanyRepository = CompanyRepository.shared) {
El view model no debería importar el repositorio. El UseCase debería de handelear esa información.

2023-10-04 18:37 UTC, lCDSLl-Richard commented on package.json
Por qué quitamos dependencies?

2023-10-04 20:29 UTC, DanielSebasCM requested changes, later dismissed
The refactor makes both android and admin not load images of the companies

2023-10-04 21:04 UTC, DHurtado714-itesm commented
> The refactor makes both android and admin not load images of the companies

Se cambio el modelo, por lo que las imagenes no se van a ver porque cambio la variable de imageUrl a fileUrl. charles esta arreglando lo de admin. Igual hay otra US que es para subir imagenes

2023-10-04 22:31 UTC, DanielSebasCM commented
Okay, se mergeea cuando eso ya quede

2023-10-04 22:35 UTC, CharlesVela66 commented
YA QUEDO ADMIN DASHBOARD ACTUALIZADO Y ESTA OPERANDO NORMALMENTE 👍

2023-10-05 20:48 UTC, DanyGuti commented on ios/GreenCircle/GreenCircle/Presentation/Views/Company/CatalogView.swift
Hay fragmentos de merge conflicts

2023-10-05 23:54 UTC, salgue441 approved these changes

2023-10-05 23:57 UTC, salgue441 requested changes, later dismissed
Las imagenes en android no funcionan correctamente. Muestra la imagen default en los proveedores que tenian imagenes como logo, productos, etc

2023-10-09 19:25 UTC, sebFlores02 commented
LGTM

2023-10-09 19:26 UTC, DavidLangarica submitted a review, later dismissed
Android funciona correctamente y ya se muestran las imágenes

2023-10-10 03:26 UTC, DavidLangarica approved these changes

2023-10-10 03:52 UTC, santiagordz approved these changes

2023-10-10 03:53 UTC, merged