Ver reseñas (cliente) | iOS
salgue441/Net-Zero-Citizens pull request #201
Opened 2023-10-04 12:06 UTC by dvegaa20

# User Story

| US ID | Module | User Story                                                                  | System  | Priority | Size | Testing | Documentation |
| ----- | ------ | --------------------------------------------------------------------------- | ------- | -------- | ---- | ------- | ------------- |
| 198   | REVIEWS   | Ver las reseñas que escribió un usuario a los diferentes proveedores | iOS | High     | 2    | Done    | Done          |

### Description

Como cliente y usuario de iOS quiero ver las reseñas hechas a diferentes proveedores.

### Acceptance Criteria

- [ ]  Debe ser posible ver las reseñas y calificaciones hechas.
- [ ]  Deben ser accesibles de manera clara y fácil de encontrar en el perfil la reseña hecha a cada proveedor.

## UI Design (or Program Flow)

<img width="233" alt="Screenshot 2023-10-04 at 6 04 32 a m" src="https://github.com/salgue441/Net-Zero-Citizens/assets/88682677/6b5de341-aa25-4a47-95e6-f8a27877e2eb">

2023-10-04 18:26 UTC, lCDSLl-Richard requested changes
En la UI el meta tag de la cantidad de reviews dice 0, cuando hay reviews en la vista.

2023-10-04 18:26 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Data/Remote/Network/ReviewService.swift
Aquí también habría que refactorizar, no debe haber un servicio, sino usar el api service desde un repositorio para hacer las calls.

2023-10-04 18:26 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Presentation/Views/Reviews/ReviewCards.swift
> +struct ReviewCardClient: View {
Mejor sacar esta view a su propio archivo.

2023-10-07 17:03 UTC, dvegaa20 commented on ios/GreenCircle/GreenCircle/Data/Remote/Network/ReviewService.swift
Se refactorizó la estructura cambiando los fetch desde NetworkAPI service y se eliminó ReviewService

2023-10-07 17:04 UTC, dvegaa20 commented
> En la UI el meta tag de la cantidad de reviews dice 0, cuando hay reviews en la vista.

2023-10-07 17:13 UTC, dvegaa20 commented
Corrected requested changes

2023-10-07 17:16 UTC, dvegaa20 reviewed
Added requested changes

2023-10-11 00:08 UTC, lCDSLl-Richard approved these changes, later dismissed

2023-10-11 11:14 UTC, dembA7 approved these changes

2023-10-11 15:55 UTC, DanyGuti approved these changes

2023-10-11 15:57 UTC, merged