Finish Landing Page for MVP
salgue441/Net-Zero-Citizens pull request #46
Opened 2023-09-13 05:04 UTC by DavidLangarica

Finished the discussed sections of the landing page for the MVP and prepared the layout for the next release

2023-09-13 05:46 UTC, lCDSLl-Richard submitted a review, later dismissed

2023-09-14 05:10 UTC, salgue441 commented
Si pueden resolver el problema del test de CodeFactor para cumplir con que todo el código siga el estándar del linter de TS

2023-09-14 05:14 UTC, salgue441 requested changes
Si pueden corregir los errores de CodeFactor para que su código cumpla con el estándar definido de TS y que pase las pruebas del linter.

2023-09-17 20:16 UTC, salgue441 approved these changes, later dismissed
Gracias por corregir lo solicitado, ahora cumple con el estándar

2023-09-18 13:17 UTC, lCDSLl-Richard submitted a review, later dismissed

2023-09-18 13:17 UTC, lCDSLl-Richard commented on Admin/src/utils/utils.ts
>  export function sum(a: number, b: number): number {
Esta función es necesaria que llegue a develop?

2023-09-18 13:17 UTC, lCDSLl-Richard commented on Admin/test/example.spec.ts
>  describe('Example Test', () => {
No hay tests reales? De ser así, entonces no necesitamos el example, o sí?

2023-09-18 13:17 UTC, lCDSLl-Richard commented on Landing/src/components/GreenTriangle.tsx
> +'use client'
Para que usamos use client aquí? No hay un hook que sea server side?

2023-09-18 13:17 UTC, lCDSLl-Richard commented on Landing/test/test.test.ts
El file name está mal, habría que usar name.spec.ts para tests

2023-09-18 13:17 UTC, lCDSLl-Richard commented on Landing/utils/sum.ts
>  export function sum(a: number, b: number): number {
Nuevamente, es necesaria esta función?

2023-09-18 13:42 UTC, DavidLangarica commented on Landing/src/components/GreenTriangle.tsx
> +'use client'
Se usó porque no hay forma en la que el servidor acceda a las propiedades de window. Por lo mismo se separo el componente y no representa ningún impacto negativo de otra forma

2023-09-18 13:52 UTC, DavidLangarica commented on Admin/test/example.spec.ts
>  describe('Example Test', () => {
Con respecto a los tests. Estos pertenecen a Admin. Seran resueltos cuando Admin tenga su respectivo PR. No se resuelven para el PR de landing

2023-09-18 13:53 UTC, DavidLangarica commented on Admin/src/utils/utils.ts
>  export function sum(a: number, b: number): number {
Al ser la Landing va a pasar a main, pues no tiene ninguna edicion que afecte la calidad de código funcional

2023-09-18 16:58 UTC, RanduRetana approved these changes
Todo se ve en orden y cumple con lo establecido

2023-09-18 17:03 UTC, CharlesVela66 approved these changes
El código cumple con el formato y está muy bien estructurado.

2023-09-20 16:50 UTC, merged