User Story: Consultar Publicaciones
salgue441/Net-Zero-Citizens pull request #50
Opened 2023-09-17 22:52 UTC by salgue441

# User Story

Como cliente quiero consultar las publicaciones realizadas por la organización para concer sobre lo que se dedica la organización y sobre el cambio climático

## Notion & Figma Link

In the following link ([EcoInfo](https://crsa.notion.site/Consultar-publicaciones-23df2377b083430c9aa72ac98872fdcc)) you can find the complete description of the User Story, as well as, the subdivision of mini stories, assignees, and corresponding sizes.

The figma approved design is in "App Móvil (Android)" and for iOS "App Móvil (iOS). [See more](https://www.figma.com/file/XBO7A8cnr7hCZ2IfU6fwEu/TC2007B-%7C-ICM?type=design&node-id=1-2&mode=design&t=yL7lOjOL66fIrJ4n-0)

## Acceptance Criteria

El cliente puede

- [x] Visualizar una lista de publicaciones por titulo
- [x] Visualizar un enlace con el nombre de 'ver más' en cada publicación que le permite ver el post completo desde facebook

## User Stories Completed

- [x] Fetch al API de META desde el backend 
- [x] Creación de UI/UX de las vistas 
- [x] Insert de datos de prueba a la base de datos
- [x] Creación del EndPoint en el backend
- [x] View & ViewModel en Android
- [x] View & ViewModel en iOS
- [x] Conexión con el backend desde Android
- [x] Conexión con el backend desde iOS
- [x] Modelo de clase de EcoInfo en backend, android e iOS

## UI for Android and iOS

<img src="https://github.com/salgue441/Net-Zero-Citizens/assets/75867326/65140613-2b47-4f2e-9a06-4258758a0ff0" height="600" alt="Screenshot 2023-09-17 161800">

<img src="https://github.com/salgue441/Net-Zero-Citizens/assets/75867326/993bf920-8773-49ed-8cbd-be6412b517b0" height="600" alt="WhatsApp Image 2023-09-17 at 14 03 45">

## Additional changes

- **Backend Linter**: variables that start with _ (e.g. _req) will not be taken as unused. This rule follows the convention that this variable witll not be used in the function but is required (as in controllers where you need req and res).
- **Backend Test Script**: added support for environment variables 
- **GitHub Actions**: set backend unit testing to accept new environment variables used for fetching the content from the facebook page (this variables are temporal, will be changed when OSF provides with their login info or token).

2023-09-18 13:27 UTC, lCDSLl-Richard requested changes, later dismissed

2023-09-18 13:27 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Data/Remote/Network/NetworkAPIService.swift
> +          .decode([EcoInfo].self, from: data)
No deberíe de decodificarse en una paginated query?

2023-09-18 13:27 UTC, lCDSLl-Richard commented on backend/src/services/ecoinfo.service.ts
> +export const getAllEcoinfo = async (): Promise<Ecoinfo[]> => {
No debería de ser un paginated service?

2023-09-18 13:27 UTC, lCDSLl-Richard commented on ios/GreenCircle/GreenCircle/Domain/UseCases/fetchAllEcoInfo.swift
> +  func limitText(ecoText: String, maxLength: Int) -> String {
Creo que truncateText es mejor nombre

2023-09-18 13:28 UTC, salgue441 commented on backend/src/services/ecoinfo.service.ts
> +export const getAllEcoinfo = async (): Promise<Ecoinfo[]> => {
Acordamos como equipo que no, que hay un máximo de noticias a mostrar y no es necesario el paginated query

2023-09-18 13:29 UTC, DiegoSandovalV commented on backend/src/services/ecoinfo.service.ts
> +export const getAllEcoinfo = async (): Promise<Ecoinfo[]> => {
Se discutió y no se le encontró un gran valor al paginado, por lo que se decidió no utilizarlo en este servicio.

2023-09-18 14:03 UTC, DanyGuti commented on ios/GreenCircle/GreenCircle/Domain/UseCases/fetchAllEcoInfo.swift
> +  func limitText(ecoText: String, maxLength: Int) -> String {
Pues sí y no

2023-09-20 17:27 UTC, DanyGuti commented on ios/GreenCircle/GreenCircle/Domain/UseCases/fetchAllEcoInfo.swift
> +  func limitText(ecoText: String, maxLength: Int) -> String {
Lo cambié a truncateText al final

2023-09-20 22:05 UTC, JP-coder2000 approved these changes

2023-09-20 22:06 UTC, DHurtado714-itesm approved these changes
LGTM!!

2023-09-20 22:06 UTC, merged